[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "Wink Saville <wink@saville.com>",
    "Henk Oordt <hd@oordt.dev>",
]
edition = "2018"
name = "registers"
version = "0.2.0"
default-run = "registers"

[dependencies]
aux7 = { path = "auxiliary" }
