[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "Wink Saville <wink@saville.com",
    "Henk Oordt <hd@oordt.dev>",
]
edition = "2018"
name = "hello-world"
version = "0.2.0"
default-run = "hello-world"

[dependencies]
aux6 = { path = "auxiliary" }

