[package]
authors = ["Jorge Aparicio <jorge@japaric.io>", "Henk Oordt <hd@oordt.dev>"]
edition = "2018"
name = "clocks-and-timers"
version = "0.1.0"
default-run = "clocks-and-timers"

[dependencies]
aux9 = { path = "auxiliary" }
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
